minerl:
  env_id: MineRLObtainDiamond-v0
  env_time_limit: 3000
  action_dim: 38
  generator_workers: 2
  gamma: 0.995
  adam_lr: 1.0e-4
  reset_interval: 50
  clip_rewards: log1p
  vecobs_weight: 10.0
  reward_weight: 10.0
  stoch_dim: 96
  kl_weight: 0.3
  entropy: 0.010
  imag_horizon: 5
  # fast mode
  batch_length: 16
  batch_size: 16
  log_interval: 300
  logbatch_interval: 2000
  save_interval: 1000
  eval_interval: 2000
